### ISSUE TITLE
Change how time is supported

### ISSUE THREAD

**Issue by riddle** [CoreNetwork/Challenges#63]
### Change CurrentWeekStart to use human-readable time

Now I think it’s number of ticks since Monday, 00:00? Something like that. Anyway, this:

``` yaml
SwitchTimeOffset: 586800
```

is unreadable to humans. It should be:

``` yaml
WeekStart: Sun, 6:00
```

or something similar (I’m rusty with timestamps).

### Support DST

Currently challenges begin one hour later or earlier, depending on which half of the year it is. It should be one fixed time.

**Comment by riddle** [comment]
BTW just commenting if my re-opening isn’t clear… this still doesn’t work. 😄 Two years of Challenges and two release dates depending on DST. Are we going to just stand and take it? Will we allow Challenges to bully us?

**Comment by narrowtux** [comment]
Nope, I'll look at it.
